### ISSUE TITLE
Make TDigest object serializable 

### ISSUE THREAD

**Issue by ynepyyvoda** [protivinsky/pytdigest#4]
I need to store TDigest object in Database for soring pre-aggregating data and further processing.
Currently, pickle.dumps(td) comes with an error 

ValueError: ctypes objects containing pointers cannot be pickled

Can you add support for TDigest object serialization or suggest a method how this can be done in alternative way.

**Comment by djgagne** [comment]
@ynepyyvoda I wrote a package called [bridgescaler](https://github.com/NCAR/bridgescaler) that uses pytdigest for its `distributed.DQuantileTransformer`. I serialize the TDigest objects using the `get_centroids()` method to extract the array storing the centroid values and weights. You can then reinitialize a TDigest object with the `of_centroids()` method. 
See [here](https://github.com/NCAR/bridgescaler/blob/3f9a6825e6da65b7afe8ea32d50305a794808ee7/bridgescaler/distributed.py#L414-L433) for an example.

**Comment by ynepyyvoda** [comment]
Thank you!

That's exactly what I need.
